# Generated by Django 5.2.6 on 2025-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalaccess',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='capitalaccess',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
