# Generated by Django 5.2.6 on 2025-11-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('copy_trading', 'Copy Trading'), ('live_trading', 'Live Trading'), ('capital_funding', 'Capital Funding'), ('consultation', 'Consultation'), ('coaching', 'Coaching'), ('general', 'General Service')], default='general', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
