# Generated by Django 5.2.6 on 2025-11-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingstrategy',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name_plural': 'Trading Strategies'},
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', help_text='Experience level required for this strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured strategies appear first'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='market_type',
            field=models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('stocks', 'Stocks'), ('commodities', 'Commodities'), ('indices', 'Indices'), ('all', 'All Markets')], default='all', help_text='Which market this strategy is designed for', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('vip', 'VIP')], default='free', help_text='Free, Premium, or VIP strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this strategy was viewed'),
        ),
    ]
