# Generated by Django 5.2.6 on 2025-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_capitalaccess_currency_capitalaccess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradewisecard',
            name='card_holder_name',
            field=models.CharField(blank=True, default='TradeWise Holder', max_length=100),
        ),
    ]
