# Generated by Django 5.2.6 on 2025-11-17 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tradewisecard_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='from_admin',
            field=models.BooleanField(default=False, help_text='Check if this review was added by admin'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user_role',
            field=models.CharField(default='Trader', help_text='e.g., Forex Trader, Crypto Trader, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('export', 'Export'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('password_reset_sent', 'Password Reset Sent'), ('system', 'System Action')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tradewisecoin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradewisecoin',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradewisecoin',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('TRANSFER', 'Transfer'), ('EARN', 'Earn')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradewisecoin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='myapp.tradeviewusers'),
        ),
    ]
