# Generated by Django 5.2.6 on 2025-11-25 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tradingstrategy_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftwareTool',
        ),
        migrations.AlterModelOptions(
            name='tradingsignal',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='accuracy_crypto',
            field=models.PositiveIntegerField(default=75, help_text='Crypto accuracy percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='accuracy_forex',
            field=models.PositiveIntegerField(default=80, help_text='Forex accuracy percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured signals appear first'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='signal_type',
            field=models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('stocks', 'Stocks'), ('all', 'All Markets')], default='forex', help_text='Type of trading signals', max_length=20),
        ),
    ]
