# Generated by Django 5.2.6 on 2025-11-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_softwaretool_alter_tradingsignal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tradeviewusers'),
        ),
    ]
