# Generated by Django 5.2.6 on 2025-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_adminlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_type', models.CharField(choices=[('software', 'Trading Software'), ('indicator', 'Trading Indicator'), ('bot', 'Trading Bot'), ('tool', 'Analysis Tool'), ('ebook', 'E-book/Guide')], default='software', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='software/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='software/thumbnails/')),
                ('compatibility', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('installation_guide', models.TextField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_kes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_vip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software Tool',
                'verbose_name_plural': 'Software Tools',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
