# Generated by Django 5.2.6 on 2025-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_servicepayment_alter_servicerequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='category',
            field=models.CharField(choices=[('caps-hats', 'Caps & Hats'), ('hoodies', 'Hoodies'), ('t-shirts', 'T-Shirts'), ('accessories', 'Accessories')], default='t-shirts', max_length=20),
        ),
    ]
