# Generated by Django 5.2.6 on 2025-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_merchandise_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchandise/'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
