# Generated by Django 5.2.6 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_merchandise_options_alter_merchandise_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='profession',
            new_name='user_role',
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='from_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
