# Generated by Django 5.2.6 on 2025-11-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_profession_review_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='coins_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
