# Generated by Django 5.2.6 on 2025-11-28 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_referral_options_referral_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklynumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weeklynumber',
            name='number',
            field=models.CharField(default='7 8 4 2 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklynumber',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('affiliate', 'referred_user')},
        ),
    ]
