# Generated by Django 5.2.6 on 2025-11-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_weeklynumber_updated_at_alter_weeklynumber_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set(),
        ),
    ]
