# Generated by Django 5.2.6 on 2025-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_referral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Affiliate', 'verbose_name_plural': 'Affiliates'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('affiliate', 'referred_user')},
        ),
    ]
